import type { Finding, PR, Repo, Review } from './types';

const PRIORITY_ORDER = ['P0', 'P1', 'P2', 'P3'] as const;

function groups(findings: Finding[]) {
  return PRIORITY_ORDER.map((p) => ({
    p,
    items: findings.filter((f) => f.priority === p),
  })).filter((g) => g.items.length > 0);
}

function loc(f: Finding): string {
  if (!f.file) return '';
  return `${f.file}${f.line != null ? `:${f.line}` : ''}`;
}

export function reviewToMarkdown(repo: Repo, pr: PR, review: Review): string {
  const out: string[] = [];
  out.push(`# Code review — ${repo.full_name} #${pr.number}`);
  out.push('');
  out.push(`**${pr.title}** · \`${pr.branch}\` → \`${pr.base_branch}\``);
  if (review.summary) {
    out.push('');
    out.push(review.summary);
  }
  out.push('');
  out.push(`_${review.findings.length} finding(s)_`);
  for (const g of groups(review.findings)) {
    out.push('', `## ${g.p} (${g.items.length})`);
    for (const f of g.items) {
      const l = loc(f);
      out.push('', `### ${f.title}${l ? ` — \`${l}\`` : ''}`);
      if (f.confidence) out.push(`_confidence: ${f.confidence}_`);
      out.push('', f.description);
      if (f.suggestion) out.push('', '**Suggestion:**', '```', f.suggestion, '```');
    }
  }
  out.push('', '---', `_Generated by gh-review-tool${review.created_at ? ` · ${review.created_at}` : ''}_`);
  return out.join('\n');
}

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export function reviewToHtml(repo: Repo, pr: PR, review: Review): string {
  const cards = groups(review.findings)
    .map((g) => {
      const items = g.items
        .map((f) => {
          const l = loc(f);
          const sugg = f.suggestion
            ? `<pre class="sugg">${esc(f.suggestion)}</pre>`
            : '';
          const conf = f.confidence ? `<span class="conf">${esc(f.confidence)}</span>` : '';
          const ref = l ? `<span class="ref">${esc(l)}</span>` : '';
          return `<div class="finding ${g.p.toLowerCase()}">
  <div class="fh"><span class="badge ${g.p.toLowerCase()}">${g.p}</span>${conf}<span class="title">${esc(f.title)}</span>${ref}</div>
  <p class="desc">${esc(f.description)}</p>${sugg}
</div>`;
        })
        .join('\n');
      return `<section><h2>${g.p} <span class="count">${g.items.length}</span></h2>${items}</section>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>Review — ${esc(repo.full_name)} #${pr.number}</title>
<style>
  :root{--bg:#0a0a0f;--card:#12121a;--bd:#2a2a3a;--tx:#e0e0e8;--mut:#8888a0;--acc:#ff6b35;
    --p0:#ff3b3b;--p1:#ff8c42;--p2:#ffd166;--p3:#7ec8e3}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--tx);font:13px/1.6 'JetBrains Mono',ui-monospace,monospace;padding:32px;max-width:920px;margin:0 auto}
  h1{font-size:19px;margin:0 0 4px}.sub{color:var(--mut);margin:0 0 16px}
  h2{font-size:14px;border-bottom:1px solid var(--bd);padding-bottom:6px;margin:24px 0 12px}
  .count{color:var(--mut);font-size:12px}
  .finding{border:1px solid var(--bd);border-left:2px solid var(--mut);border-radius:8px;padding:12px 14px;margin:8px 0;background:var(--card)}
  .finding.p0{border-left-color:var(--p0)}.finding.p1{border-left-color:var(--p1)}
  .finding.p2{border-left-color:var(--p2)}.finding.p3{border-left-color:var(--p3)}
  .fh{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
  .badge{font-size:10px;font-weight:800;padding:2px 6px;border-radius:3px}
  .badge.p0{background:rgba(255,59,59,.15);color:var(--p0)}.badge.p1{background:rgba(255,140,66,.15);color:var(--p1)}
  .badge.p2{background:rgba(255,209,102,.15);color:var(--p2)}.badge.p3{background:rgba(126,200,227,.15);color:var(--p3)}
  .conf{font-size:10px;color:#4ecdc4;text-transform:uppercase}
  .title{font-weight:600}.ref{color:var(--mut);font-size:11px;font-style:italic}
  .desc{color:var(--mut);margin:8px 0}
  pre.sugg{background:#0c0c12;border:1px solid var(--bd);border-radius:5px;padding:10px;white-space:pre-wrap;font-size:11px;color:#9fe8e2;overflow-x:auto}
  .summary{white-space:pre-wrap;color:var(--mut);border:1px solid var(--bd);border-radius:8px;padding:12px;background:var(--card)}
  footer{color:var(--mut);font-size:11px;margin-top:28px;border-top:1px solid var(--bd);padding-top:10px}
</style></head><body>
<h1>Code review — ${esc(repo.full_name)} #${pr.number}</h1>
<p class="sub">${esc(pr.title)} · ${esc(pr.branch)} → ${esc(pr.base_branch)} · ${review.findings.length} finding(s)</p>
${review.summary ? `<div class="summary">${esc(review.summary)}</div>` : ''}
${cards}
<footer>Generated by gh-review-tool${review.created_at ? ` · ${esc(review.created_at)}` : ''}</footer>
</body></html>`;
}

export function downloadFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
